### ISSUE TITLE
Erro ao instalar dependências

### ISSUE THREAD

**Issue by xfeliper6** [eudanilobarbosa/cypress-express#1]
Ao tentar instalar as dependencias ocorre o seguinte erro.
Usando as versões do node, npm e git indicadas, poderia me ajudar? 

npm ERR! path C:\qax\apps\markl\api\node_modules\better-sqlite3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild --release
npm ERR! '"node"' n�o � reconhecido como um comando interno
npm ERR! ou externo, um programa oper�vel ou um arquivo em lotes.
npm ERR! 'node' n�o � reconhecido como um comando interno
npm ERR! ou externo, um programa oper�vel ou um arquivo em lotes.

**Comment by eudanilobarbosa** [comment]
@xfeliper6 esse erro ocorre quando o comando node `npm` não é reconhecido pelo sistema, geralmente porque o **Node.js não está instalado ou não está configurado corretamente no PATH do Windows**.

Para confirmar, abra o prompt de comando do Windows e execute o comando `node -v` se o Node.js estiver instalado, esse comando mostrará a versão do Node. Caso contrário, ele retornará uma mensagem de erro, e para resolver basta re-instalar o node e durante a instalação, certifique-se de marcar a opção para **adicionar o Node.js ao PATH do sistema**, acredito que essa é a opção mais fácil.

Confirme se deu certo e qualquer dúvida comenta nessa mesma _issue_, abraço e bons estudos! 🤖

**Comment by xfeliper6** [comment]
@eudanilobarbosa o comando npm não estava sendo reconhecido pelo Git Bash, ao executa-lo no prompt do windows terminal funcionou normalmente.
Obrigado!
